# Copyright (c) 2020 Sybsuper
# All Rights Reserved
# Do not use this code without permission of the developer.
ticksBeforeCheck: 4
maxDifference: 0.025
delayBeforeRunBotCheck: 100
delayedChecks: 3
default:
  yaw: 3.0
  pitch: 3.0
ores:
  - IRON_ORE
  - GOLD_ORE
  - DIAMOND_ORE
  - EMERALD_ORE
  - COAL_ORE
  - LAPIS_ORE
  - REDSTONE_ORE
  - QUARTZ_ORE
  - LOG
  - LOG_2
  - OAK_LOG
  - BIRCH_LOG
  - JUNGLE_LOG
  - ACACIA_LOG
  - DARK_OAK_LOG
  - SPRUCE_LOG
messages:
  reloadSuccess: "&2Successfully reloaded config files."
  reloadNoPermission: "&cYou don't have permission to execute this command."
  playerAlreadyBeingChecked: "&cThat player is already being checked."
  playerDoesNotExist: "&cThat player does not exist."
  noPermission: "&cYou don't have permission to execute this command."
checkChanceOnOreMine: 0.05
setback: false
enableBypassPermission: true
violations: 2
clearViolations: 600
notify:
  enable: true
  message: "&f[&cSybAntiBot&f] &l%player% &7might be using an &f&lauto-mine bot&7 (&f%violations%VL&7)."
commands:
  - "kick %player% Bots are not allowed."
return:
  bot: "&4%player% is probably a bot. (Pitch: %pitch%, Yaw: %yaw%)"
  noBot: "&2%player% is not a bot. (Pitch: %pitch%, Yaw: %yaw%)"
log:
  enable: true
  bot: "%player% is a bot. p: %pitch%, y: %yaw%"
  noBot: "%player% is not a bot. p: %pitch%, y: %yaw%"