name: SybAntiBot
main: me.sybsuper.SybAntiBot.Main
version: 1.1.1
commands:
  isbot:
    aliases: [rot]
    permission: sybantibot.use
    permission-message: You don't have permission to execute this command.
    usage: /isbot <player> [yaw] [pitch]